import {IColorListType} from "@/types/utils/IColorListType";

export const color_list: IColorListType[] = [
    { name: 'Black', hex: '#000000' },
    { name: 'Dim Gray', hex: '#696969' },
    { name: 'Gray', hex: '#808080' },
    { name: 'Light Slate Gray', hex: '#778899' },
    { name: 'Slate Gray', hex: '#708090' },
    { name: 'Dark Gray', hex: '#A9A9A9' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Light Gray', hex: '#D3D3D3' },
    { name: 'Gainsboro', hex: '#DCDCDC' },
    { name: 'White Smoke', hex: '#F5F5F5' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Snow', hex: '#FFFAFA' },
    { name: 'Rosy Brown', hex: '#BC8F8F' },
    { name: 'Light Coral', hex: '#F08080' },
    { name: 'Indian Red', hex: '#CD5C5C' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Firebrick', hex: '#B22222' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Dark Red', hex: '#8B0000' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Salmon', hex: '#FA8072' },
    { name: 'Tomato', hex: '#FF6347' },
    { name: 'Dark Salmon', hex: '#E9967A' },
    { name: 'Coral', hex: '#FF7F50' },
    { name: 'Orange Red', hex: '#FF4500' },
    { name: 'Light Salmon', hex: '#FFA07A' },
    { name: 'Sienna', hex: '#A0522D' },
    { name: 'Chocolate', hex: '#D2691E' },
    { name: 'Saddle Brown', hex: '#8B4513' },
    { name: 'Sandy Brown', hex: '#F4A460' },
    { name: 'Peru', hex: '#CD853F' },
    { name: 'Dark Orange', hex: '#FF8C00' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Dark Golden Rod', hex: '#B8860B' },
    { name: 'Golden Rod', hex: '#DAA520' },
    { name: 'Gold', hex: '#FFD700' },
    { name: 'Khaki', hex: '#F0E68C' },
    { name: 'Dark Khaki', hex: '#BDB76B' },
    { name: 'Olive', hex: '#808000' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Olive Drab', hex: '#6B8E23' },
    { name: 'Yellow Green', hex: '#9ACD32' },
    { name: 'Dark Olive Green', hex: '#556B2F' },
    { name: 'Green Yellow', hex: '#ADFF2F' },
    { name: 'Chartreuse', hex: '#7FFF00' },
    { name: 'Dark Sea Green', hex: '#8FBC8F' },
    { name: 'Pale Green', hex: '#98FB98' },
    { name: 'Light Green', hex: '#90EE90' },
    { name: 'Forest Green', hex: '#228B22' },
    { name: 'Lime Green', hex: '#32CD32' },
    { name: 'Dark Green', hex: '#006400' },
    { name: 'Green', hex: '#008000' },
    { name: 'Lime', hex: '#00FF00' },
    { name: 'Sea Green', hex: '#2E8B57' },
    { name: 'Medium Sea Green', hex: '#3CB371' },
    { name: 'Spring Green', hex: '#00FF7F' },
    { name: 'Medium Spring Green', hex: '#00FA9A' },
    { name: 'Medium Aquamarine', hex: '#66CDAA' },
    { name: 'Aquamarine', hex: '#7FFFD4' },
    { name: 'Turquoise', hex: '#40E0D0' },
    { name: 'Light Sea Green', hex: '#20B2AA' },
    { name: 'Medium Turquoise', hex: '#48D1CC' },
    { name: 'Dark Slate Gray', hex: '#2F4F4F' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Dark Cyan', hex: '#008B8B' },
    { name: 'Aqua', hex: '#00FFFF' },
    { name: 'Dark Turquoise', hex: '#00CED1' },
    { name: 'Cadet Blue', hex: '#5F9EA0' },
    { name: 'Deep Sky Blue', hex: '#00BFFF' },
    { name: 'Light Sky Blue', hex: '#87CEFA' },
    { name: 'Steel Blue', hex: '#4682B4' },
    { name: 'Dodger Blue', hex: '#1E90FF' },
    { name: 'Light Steel Blue', hex: '#B0C4DE' },
    { name: 'Cornflower Blue', hex: '#6495ED' },
    { name: 'Royal Blue', hex: '#4169E1' },
    { name: 'Midnight Blue', hex: '#191970' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Dark Blue', hex: '#00008B' },
    { name: 'Medium Blue', hex: '#0000CD' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Slate Blue', hex: '#6A5ACD' },
    { name: 'Dark Slate Blue', hex: '#483D8B' },
    { name: 'Medium Slate Blue', hex: '#7B68EE' },
    { name: 'Medium Purple', hex: '#9370DB' },
    { name: 'Rebecca Purple', hex: '#663399' },
    { name: 'Blue Violet', hex: '#8A2BE2' },
    { name: 'Indigo', hex: '#4B0082' },
    { name: 'Dark Orchid', hex: '#9932CC' },
    { name: 'Dark Violet', hex: '#9400D3' },
    { name: 'Medium Orchid', hex: '#BA55D3' },
    { name: 'Pink', hex: '#FFC0CB' },
    { name: 'Light Pink', hex: '#FFB6C1' },
    { name: 'Thistle', hex: '#D8BFD8' },
    { name: 'Plum', hex: '#DDA0DD' },
    { name: 'Violet', hex: '#EE82EE' },
    { name: 'Orchid', hex: '#DA70D6' },
    { name: 'Magenta', hex: '#FF00FF' },
    { name: 'Fuchsia', hex: '#FF00FF' },
    { name: 'Purple', hex: '#800080' },
    { name: 'Dark Magenta', hex: '#8B008B' },
    { name: 'Medium Violet Red', hex: '#C71585' },
    { name: 'Deep Pink', hex: '#FF1493' },
    { name: 'Hot Pink', hex: '#FF69B4' },
    { name: 'Pale Violet Red', hex: '#DB7093' },
    { name: 'Crimson', hex: '#DC143C' },
]
